#!/usr/bin/env python3
"""Compile a scene into scene_embedded.h, for the sketch's standalone mode.

    python embed_scene.py ../../scenes/three-strokes.json   # a scene document, as is
    python embed_scene.py screen.html                        # screen-HTML, via drm_composer

Screen-HTML becomes one whole-screen document (`drm_composer.emit_screen_json`):
<box>, <text> and <path> in any layer, layers kept by z. <img> and <button>
have no scene form and are refused, since the panel could not draw them.

Writes scene_embedded.h beside this script unless -o says otherwise. The
header is committed, so the sketch builds without running this first.
"""

import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
DELIMITER = "mm_scene"


def compile_source(path: pathlib.Path) -> bytes:
    if path.suffix.lower() == ".json":
        return json.dumps(json.loads(path.read_text()), separators=(",", ":")).encode()
    try:
        from drm_composer import emit_screen_json, parse_scene
    except ImportError:
        sys.exit("drm_composer with emit_screen_json is needed for screen-HTML: "
                 "pip install -e ~/code/drm_composer")
    return emit_screen_json(parse_scene(path.read_text()), name=path.stem)


def header(document: bytes, source: pathlib.Path) -> str:
    text = document.decode()
    if f"){DELIMITER}\"" in text:
        sys.exit(f"the scene contains the raw-string terminator ){DELIMITER}\"")
    return (
        f"// Generated by embed_scene.py from {source.name} -- regenerate, don't edit.\n"
        f"// {len(document)} bytes of drm_scene_ir, loaded by the sketch when\n"
        f"// MM_STANDALONE is 1.\n"
        f"#pragma once\n\n"
        f"static const char MM_EMBEDDED_SCENE[] = R\"{DELIMITER}({text}){DELIMITER}\";\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("source", type=pathlib.Path, help="screen-HTML or scene JSON")
    parser.add_argument("-o", "--out", type=pathlib.Path, default=HERE / "scene_embedded.h")
    args = parser.parse_args()

    document = compile_source(args.source)
    args.out.write_text(header(document, args.source))
    print(f"{args.out}: {len(document)} bytes from {args.source}")


if __name__ == "__main__":
    main()
